### ISSUE TITLE
API danh sách khách hàng, khách hàng đã xóa tìm theo keyword nhưng data chưa đúng

### ISSUE THREAD

**Issue by vandiepbui** [soga-software/P201108_phone_management#12]
![image](https://user-images.githubusercontent.com/35633954/101989931-2b2d7780-3cd6-11eb-8b3c-6a8604480f1e.png)

tìm keyword nhưng chưa thấy trả về data đúng với keyword

**Comment by soga-software** [comment]
Đã chỉnh sữa lại mục lọc keyword
