### ISSUE TITLE
Get danh sách user khi đăng nhập bằng tài khoản admin trả về id null

### ISSUE THREAD

**Issue by vandiepbui** [soga-software/P201108_phone_management#2]

**Comment by soga-software** [comment]
Đã fix lại lỗi null do trùng trường id giữa 2 bảng, nên nếu không chỉ định chọn id trong bảng nào thì id trong laravel bị đặt là null
![image](https://user-images.githubusercontent.com/53817618/101976577-18388a00-3c79-11eb-9dcb-1a1219778b24.png)
