### ISSUE TITLE
Các api cần sửa errors thành mảng

### ISSUE THREAD

**Issue by vandiepbui** [soga-software/P201108_phone_management#5]
1./ Đăng ký: 
![image](https://user-images.githubusercontent.com/35633954/101855750-8a846e00-3b96-11eb-9407-4701959dea28.png)

2./ Xác thực code khi đăng ký
3./ xác thực code khi quên mật khẩu
4./ Cập nhật số ngày tự động block tài khoản
![image](https://user-images.githubusercontent.com/35633954/101855841-b9024900-3b96-11eb-99ee-fc892e13054c.png)

**Comment by soga-software** [comment]
Các phần trên đã fix, còn phần này tôi chưa tìm thấy vị trí lỗi, ông chụp màn hình giúp tui nha
4./ Cập nhật số ngày tự động block tài khoản

**Comment by vandiepbui** [comment]
Cái này chỉ xảy ra khi k đủ quyền thôi ông. Ví dụ login bằng sub admin mà vô gọi api này thì lỗi. Chắc k xảy ra đâu. Do trên app t phân quyền rồi
