### ISSUE TITLE
Danh sách account get theo keyword, tỉnh thành, trạng thái tài khoản và page

### ISSUE THREAD

**Issue by vandiepbui** [soga-software/P201108_phone_management#6]
Tuỳ vào role của user đang login mà param truyền lên sẽ khác:

1./ sub admin: chỉ quản lý 1 tỉnh thành do admin set khi cấp quyền cho từng sub admin
Params truyền lên:
   - manage_city_id: (param bắt buộc) ở api get thông tin user login, ông filter nếu role_id === 2 (sub admin) thì ông trả cho tôi thêm 1 trường là manage_city_id. để tôi biết thằng sub admin đó nó quản lý tỉnh thành nào. khi nó login vô app, nhấn vào trang danh sách người dùng thì tôi lấy cái manage_city_id đó tôi gởi vô param cho ông trả về danh sách người dùng thuộc tỉnh nó quản lý thôi.

   - account_status: (param không bắt buộc) trạng thái tài khoản ở đây là đang bị khoá hoặc đang hoạt động (Active) để cho dễ quản lý tài khoản
  - keyword: (param không bắt buộc) từ khoá nhập vào ô tìm kiếm (có thể là email, phone, họ tên người dùng)
  - page: (param bắt buộc) load danh sách theo trang

2./ Admin: thằng này quản lý toàn bộ user trong app
Params gồm 3 param (account_status, keyword, page). chỉ có page là param bắt buộc

Lưu ý: danh sách account trả về nhớ bỏ thằng user đang login ra. ví dụ tôi login bằng user có email là admin@gmail.com thì khi tôi vào trang danh sách người dùng, ông bỏ thằng user này ra. (1 tài khoản k quản lý chính nó, nên k cần hiện lên, mắc công nó block nó nữa)

**Comment by soga-software** [comment]
Đã điều chỉnh theo yêu cầu

**Comment by soga-software** [comment]
Danh sách param là :
"keyword" : "sub",
"page" : 1
"city_id" : 1
"is_block": 1 (1 hoặc 0)

**Comment by soga-software** [comment]
Không cần thêm city_id nha ông, nếu role 2 hệ thống sẽ tự lọc được
