### ISSUE TITLE
Thêm api cập nhật role cho user

### ISSUE THREAD

**Issue by vandiepbui** [soga-software/P201108_phone_management#7]
api này chỉ admin mới có quyền truy cập. để nâng người dùng lên sub admin hoặc admin. set tỉnh thành quản lý cho sub admin. thằng sub admin không có quyền nâng người dùng lên thành sub admin hay admin được.

header: token,
params:
 - id: (param bắt buộc) id của thằng user được cập nhật role,
 - role_id: (param bắt buộc)  1 hoặc 2 hoặc 3
 - manage_city_id: (param chỉ bắt buộc nếu role_id === 2) nếu chọn role là sub admin thì bắt buộc phải chọn tỉnh thành cho sub admin đó quản lý.

Lưu ý: api này dùng chung cho nâng quyền và hạ quyền 1 user. có thể hiểu là update role. khi set quyền xong ông nhớ clear cái token của thằng user được update role. mục đích để bắt nó login lại sử dụng role mới được update

**Comment by soga-software** [comment]
![image](https://user-images.githubusercontent.com/53817618/101980200-585a3580-3c96-11eb-8aa0-cd7a639e7846.png)
Đã cập nhật :
Nâng quyền: Chỉ có thể nâng từ user lên subadmin. Đối số gồm id user và id tỉnh thành
Nâng cấp phân quyền: Chỉ cần id user sẽ chuyển từ user thường thành subadmin
Không nâng lên cấp admin, khi nào cần sẽ cấp cứng, vì admin không có khả năng block và hạ phân quyền. Nếu nâng lên mà user gây ảnh hưởng hệ thống sẽ không hạ được

**Comment by vandiepbui** [comment]
Hạ quyền từ sub admin xuống user thường thì sao ông

**Comment by vandiepbui** [comment]
Với tỉnh nào có sub admin quản lý rồi thì ông nhớ check k cho set cho sub admin khác nữa nhé

**Comment by soga-software** [comment]
> Với tỉnh nào có sub admin quản lý rồi thì ông nhớ check k cho set cho sub admin khác nữa nhé

Đã chỉnh sửa nha ông. Nếu có sub rồi mà thêm sub nửa sẽ bị cảnh báo

**Comment by soga-software** [comment]
> Hạ quyền từ sub admin xuống user thường thì sao ông

Có api hạ quyền rồi ông, truyền id người bị hạ quyền là được ak
![Uploading image.png…]()

**Comment by soga-software** [comment]
> Hạ quyền từ sub admin xuống user thường thì sao ông

Có api hạ quyền rồi ông, truyền id người bị hạ quyền là được ak
![image](https://user-images.githubusercontent.com/53817618/102004821-daa23280-3d46-11eb-800f-9ddb147f0466.png)
